services:
  zmk-build-container:
    container_name: zmk-build-container
    tty: true
    build:
      dockerfile: ./dockerfiles/Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ~/Documents/projects/keebs/zmk-config-personal/build:/workspaces/zmk/app/build/zephyr
