services:
  zmk-build-container:
    container_name: zmk-build-container
    tty: true
    build:
      context: ./zmk/.devcontainer
      dockerfile: Dockerfile
    working_dir: /workspaces/zmk
    ports:
      - 3000:3000
    volumes:
      - ./zmk:/workspaces/zmk
      - $ROOT_DIR/config:/workspaces/zmk/zmk-config
      - $ROOT_DIR/modules:/workspaces/zmk/zmk-modules
